In [3]:
import numpy as np
test_data = np.load('data/test.npz')
x_test, y_test, seq_len_test = test_data['X'], test_data['y'], test_data['seq_len']

In [4]:
def flatten_sequence(inp, seq_len):
    result = None
    for i in range(inp.shape[0]):
        if result is not None:
            result = np.concatenate((result, inp[i, :, :int(seq_len[i])]), axis=1)
        else:
            result = inp[i, :, :int(seq_len[i])]
    return result
        

In [5]:
from feature import feature_apply

In [6]:
x_test = feature_apply(x_test, seq_len_test, x_test).astype('float32')

In [7]:
x_test.shape

(534, 16, 700)

In [8]:
total_x = x_test.transpose((1, 0, 2))

In [9]:
total_x.shape

(16, 534, 700)

In [10]:
total_x = flatten_sequence(x_test, seq_len_test)

In [11]:
total_x.shape

(16, 111206)

In [12]:
total_x = total_x.transpose()

In [13]:
y_test.shape

(534, 700)

In [14]:
total_y = y_test.reshape((-1))

In [15]:
total_y

array([0., 0., 7., ..., 0., 0., 0.], dtype=float32)

In [16]:
from model_wrapper import map_q8_to_q3
mapper = np.vectorize(map_q8_to_q3)
total_y = mapper(y_test).reshape((534, 1, -1))
resp = np.concatenate((total_y == 0, total_y == 1, total_y == 2), axis=1)

In [17]:
total_y = flatten_sequence(resp, seq_len_test)
total_y.shape

(3, 111206)

In [18]:
print(total_y.shape)
r_h = total_y[0, :]
r_e = total_y[1, :]
r_l = total_y[2, :]

(3, 111206)


In [19]:
result = result.transpose()

NameError: name 'result' is not defined

In [46]:
total_x = total_x.transpose()

In [47]:
import matplotlib.pyplot as plt

In [48]:
el = total_x[0, :]

In [49]:
hyd = total_x[1, :]

In [50]:
pol = total_x[2, :]

In [51]:
vol = total_x[3, :]
s0 = total_x[4, :]
s1 = total_x[5, :]
s2 = total_x[6, :]
el_m = total_x[7, :]
hyd_m = total_x[8, :]
pol_m = total_x[9, :]
vol_m = total_x[10, :]
s0_m = total_x[11, :]
s1_m = total_x[12, :]
s2_m = total_x[13, :]

In [52]:
r_h.shape

(111206,)

In [53]:
print(np.corrcoef(el, r_h))
print(np.corrcoef(el, r_e))
print(np.corrcoef(el, r_l))

[[1.         0.07717206]
 [0.07717206 1.        ]]
[[ 1.        -0.1573195]
 [-0.1573195  1.       ]]
[[1.         0.06087351]
 [0.06087351 1.        ]]


In [54]:
print(np.corrcoef(hyd, r_h))
print(np.corrcoef(hyd, r_e))
print(np.corrcoef(hyd, r_l))

[[1.         0.11214094]
 [0.11214094 1.        ]]
[[1.         0.01021359]
 [0.01021359 1.        ]]
[[ 1.         -0.12086232]
 [-0.12086232  1.        ]]


In [55]:
print(np.corrcoef(pol, r_h))
print(np.corrcoef(pol, r_e))
print(np.corrcoef(pol, r_l))

[[ 1.         -0.03179397]
 [-0.03179397  1.        ]]
[[ 1.         -0.11407019]
 [-0.11407019  1.        ]]
[[1.         0.13170846]
 [0.13170846 1.        ]]


In [56]:
print(np.corrcoef(vol, r_h))
print(np.corrcoef(vol, r_e))
print(np.corrcoef(vol, r_l))

[[1.         0.04269166]
 [0.04269166 1.        ]]
[[1.         0.06769901]
 [0.06769901 1.        ]]
[[ 1.         -0.10194049]
 [-0.10194049  1.        ]]


In [57]:
print(np.corrcoef(el_m, r_h))
print(np.corrcoef(el_m, r_e))
print(np.corrcoef(el_m, r_l))

[[1.         0.02564356]
 [0.02564356 1.        ]]
[[ 1.         -0.02662686]
 [-0.02662686  1.        ]]
[[ 1.         -0.00225301]
 [-0.00225301  1.        ]]


In [58]:
print(np.corrcoef(hyd_m, r_h))
print(np.corrcoef(hyd_m, r_e))
print(np.corrcoef(hyd_m, r_l))

[[ 1.         -0.05809332]
 [-0.05809332  1.        ]]
[[ 1.         -0.05057774]
 [-0.05057774  1.        ]]
[[1.         0.10230407]
 [0.10230407 1.        ]]


In [59]:
print(np.corrcoef(pol_m, r_h))
print(np.corrcoef(pol_m, r_e))
print(np.corrcoef(pol_m, r_l))

[[ 1.        -0.0673135]
 [-0.0673135  1.       ]]
[[ 1.       -0.045033]
 [-0.045033  1.      ]]
[[1.         0.10664546]
 [0.10664546 1.        ]]


In [60]:
print(np.corrcoef(vol_m, r_h))
print(np.corrcoef(vol_m, r_e))
print(np.corrcoef(vol_m, r_l))

[[ 1.         -0.04632258]
 [-0.04632258  1.        ]]
[[1.         0.03561576]
 [0.03561576 1.        ]]
[[1.         0.01501094]
 [0.01501094 1.        ]]


In [61]:
print(np.corrcoef(s0, r_h))
print(np.corrcoef(s0, r_e))
print(np.corrcoef(s0, r_l))

[[1.         0.07732963]
 [0.07732963 1.        ]]
[[1.         0.11604328]
 [0.11604328 1.        ]]
[[ 1.         -0.17887986]
 [-0.17887986  1.        ]]


In [62]:
print(np.corrcoef(s1, r_h))
print(np.corrcoef(s1, r_e))
print(np.corrcoef(s1, r_l))

[[ 1.         -0.01012307]
 [-0.01012307  1.        ]]
[[ 1.         -0.16220457]
 [-0.16220457  1.        ]]
[[1.        0.1522708]
 [0.1522708 1.       ]]


In [63]:
print(np.corrcoef(s2, r_h))
print(np.corrcoef(s2, r_e))
print(np.corrcoef(s2, r_l))

[[1.         0.07028986]
 [0.07028986 1.        ]]
[[ 1.         -0.15403702]
 [-0.15403702  1.        ]]
[[1.         0.06486455]
 [0.06486455 1.        ]]


In [64]:
print(np.corrcoef(s0_m, r_h))
print(np.corrcoef(s0_m, r_e))
print(np.corrcoef(s0_m, r_l))

[[ 1.         -0.02218588]
 [-0.02218588  1.        ]]
[[1.         0.07087989]
 [0.07087989 1.        ]]
[[ 1.         -0.03998432]
 [-0.03998432  1.        ]]


In [65]:
print(np.corrcoef(s1_m, r_h))
print(np.corrcoef(s1_m, r_e))
print(np.corrcoef(s1_m, r_l))

[[1.         0.04412672]
 [0.04412672 1.        ]]
[[ 1.         -0.05247372]
 [-0.05247372  1.        ]]
[[1.         0.00195602]
 [0.00195602 1.        ]]


In [66]:
print(np.corrcoef(s2_m, r_h))
print(np.corrcoef(s2_m, r_e))
print(np.corrcoef(s2_m, r_l))

[[ 1.         -0.05451324]
 [-0.05451324  1.        ]]
[[ 1.         -0.07011933]
 [-0.07011933  1.        ]]
[[1.         0.11585911]
 [0.11585911 1.        ]]


In [67]:
out = np.load('output.npy')

In [68]:
out = out.transpose(0, 2, 1)

In [69]:
predicted = flatten_sequence(out, seq_len_test)

In [70]:
predicted.shape

(8, 111206)

In [71]:
out_h = predicted[3:6, :].sum(axis=0)
out_l = predicted[np.array([0, 6, 7]), :].sum(axis=0)
out_e = predicted[1:3, :].sum(axis=0)
out_h.shape

(111206,)

In [72]:
print(np.corrcoef(el, out_h))
print(np.corrcoef(el, out_e))
print(np.corrcoef(el, out_l))

[[1.         0.06772464]
 [0.06772464 1.        ]]
[[ 1.         -0.15148401]
 [-0.15148401  1.        ]]
[[1.         0.07701881]
 [0.07701881 1.        ]]


In [73]:
print(np.corrcoef(hyd, out_h))
print(np.corrcoef(hyd, out_e))
print(np.corrcoef(hyd, out_l))

[[1.        0.1041413]
 [0.1041413 1.       ]]
[[1.         0.03133362]
 [0.03133362 1.        ]]
[[ 1.         -0.14158919]
 [-0.14158919  1.        ]]


In [74]:
print(np.corrcoef(pol, out_h))
print(np.corrcoef(pol, out_e))
print(np.corrcoef(pol, out_l))

[[ 1.        -0.0436218]
 [-0.0436218  1.       ]]
[[ 1.         -0.09570254]
 [-0.09570254  1.        ]]
[[1.         0.14055717]
 [0.14055717 1.        ]]


In [75]:
print(np.corrcoef(vol, out_h))
print(np.corrcoef(vol, out_e))
print(np.corrcoef(vol, out_l))

[[1.         0.03516929]
 [0.03516929 1.        ]]
[[1.         0.10055865]
 [0.10055865 1.        ]]
[[ 1.         -0.13634551]
 [-0.13634551  1.        ]]


In [76]:
print(np.corrcoef(el_m, out_h))
print(np.corrcoef(el_m, out_e))
print(np.corrcoef(el_m, out_l)) 

[[1.         0.02098608]
 [0.02098608 1.        ]]
[[ 1.         -0.02659987]
 [-0.02659987  1.        ]]
[[1.         0.00385225]
 [0.00385225 1.        ]]


In [77]:
print(np.corrcoef(hyd_m, out_h))
print(np.corrcoef(hyd_m, out_e))
print(np.corrcoef(hyd_m, out_l))

[[ 1.         -0.06157974]
 [-0.06157974  1.        ]]
[[ 1.        -0.0477841]
 [-0.0477841  1.       ]]
[[1.         0.11250867]
 [0.11250867 1.        ]]


In [78]:
print(np.corrcoef(pol_m, out_h))
print(np.corrcoef(pol_m, out_e))
print(np.corrcoef(pol_m, out_l))

[[ 1.         -0.07231094]
 [-0.07231094  1.        ]]
[[ 1.         -0.05234212]
 [-0.05234212  1.        ]]
[[1.         0.12840656]
 [0.12840656 1.        ]]


In [79]:
print(np.corrcoef(vol_m, out_h))
print(np.corrcoef(vol_m, out_e))
print(np.corrcoef(vol_m, out_l))

[[ 1.         -0.04709585]
 [-0.04709585  1.        ]]
[[1.        0.0352069]
 [0.0352069 1.       ]]
[[1.         0.01544823]
 [0.01544823 1.        ]]


In [80]:
print(np.corrcoef(s0, out_h))
print(np.corrcoef(s0, out_e))
print(np.corrcoef(s0, out_l))

[[1.         0.06897128]
 [0.06897128 1.        ]]
[[1.         0.14626397]
 [0.14626397 1.        ]]
[[ 1.         -0.21726578]
 [-0.21726578  1.        ]]


In [81]:
print(np.corrcoef(s1, out_h))
print(np.corrcoef(s1, out_e))
print(np.corrcoef(s1, out_l))

[[ 1.         -0.03135456]
 [-0.03135456  1.        ]]
[[ 1.         -0.14577042]
 [-0.14577042  1.        ]]
[[1.         0.17677288]
 [0.17677288 1.        ]]


In [82]:
print(np.corrcoef(s2, out_h))
print(np.corrcoef(s2, out_e))
print(np.corrcoef(s2, out_l))

[[1.         0.05807719]
 [0.05807719 1.        ]]
[[ 1.         -0.13768601]
 [-0.13768601  1.        ]]
[[1.        0.0737033]
 [0.0737033 1.       ]]


In [83]:
print(np.corrcoef(s0_m, out_h))
print(np.corrcoef(s0_m, out_e))
print(np.corrcoef(s0_m, out_l))

[[ 1.         -0.01800976]
 [-0.01800976  1.        ]]
[[1.         0.07822605]
 [0.07822605 1.        ]]
[[ 1.         -0.05781349]
 [-0.05781349  1.        ]]


In [84]:
print(np.corrcoef(s1_m, out_h))
print(np.corrcoef(s1_m, out_e))
print(np.corrcoef(s1_m, out_l))

[[1.         0.04417489]
 [0.04417489 1.        ]]
[[ 1.         -0.05135951]
 [-0.05135951  1.        ]]
[[1.         0.00355116]
 [0.00355116 1.        ]]


In [85]:
print(np.corrcoef(s2_m, out_h))
print(np.corrcoef(s2_m, out_e))
print(np.corrcoef(s2_m, out_l))

[[ 1.         -0.06731082]
 [-0.06731082  1.        ]]
[[ 1.        -0.0954729]
 [-0.0954729  1.       ]]
[[1.         0.16552571]
 [0.16552571 1.        ]]


In [86]:
def aggregate_from_surrouding(inp, sur_size=8):
    res = np.zeros(inp.shape)
    for i in range(inp.shape[0]):
        for j in range(inp.shape[1]):
            beg = max(j - sur_size, 0)
            end = min(j + sur_size, inp.shape[1] - 1)
            res[i, j] = np.absolute(inp[i, beg:end]).mean()
    return res
        

In [87]:
aggregated_x = aggregate_from_surrouding(total_x)

In [88]:
aggregated_x.shape

(16, 111206)

In [89]:
a_el = aggregated_x[0, :]
a_hyd = aggregated_x[1, :]
a_pol = aggregated_x[2, :]
a_vol = aggregated_x[3, :]
a_s0 = aggregated_x[4, :]
a_s1 = aggregated_x[5, :]
a_s2 = aggregated_x[6, :]
a_el_m = aggregated_x[7, :]
a_hyd_m = aggregated_x[8, :]
a_pol_m = aggregated_x[9, :]
a_vol_m = aggregated_x[10, :]
a_s0_m = aggregated_x[11, :]
a_s1_m = aggregated_x[12, :]
a_s2_m = aggregated_x[13, :]


In [90]:
print(np.corrcoef(a_el, out_h))
print(np.corrcoef(a_el, out_e))
print(np.corrcoef(a_el, out_l))

[[1.         0.08165792]
 [0.08165792 1.        ]]
[[ 1.         -0.06980212]
 [-0.06980212  1.        ]]
[[ 1.         -0.01816799]
 [-0.01816799  1.        ]]


In [91]:
print(np.corrcoef(a_hyd, out_h))
print(np.corrcoef(a_hyd, out_e))
print(np.corrcoef(a_hyd, out_l))

[[1.        0.0714453]
 [0.0714453 1.       ]]
[[ 1.         -0.01964247]
 [-0.01964247  1.        ]]
[[ 1.         -0.05665918]
 [-0.05665918  1.        ]]


In [92]:
print(np.corrcoef(a_pol, out_h))
print(np.corrcoef(a_pol, out_e))
print(np.corrcoef(a_pol, out_l))

[[ 1.         -0.06195029]
 [-0.06195029  1.        ]]
[[1.         0.06577105]
 [0.06577105 1.        ]]
[[1.         0.00117415]
 [0.00117415 1.        ]]


In [93]:
print(np.corrcoef(a_s0, out_h))
print(np.corrcoef(a_s0, out_e))
print(np.corrcoef(a_s0, out_l))

[[1.         0.02048338]
 [0.02048338 1.        ]]
[[1.         0.03098565]
 [0.03098565 1.        ]]
[[ 1.         -0.05227236]
 [-0.05227236  1.        ]]


In [94]:
print(np.corrcoef(a_s1, out_h))
print(np.corrcoef(a_s1, out_e))
print(np.corrcoef(a_s1, out_l))

[[ 1.         -0.05334797]
 [-0.05334797  1.        ]]
[[1.         0.02346969]
 [0.02346969 1.        ]]
[[1.         0.03364609]
 [0.03364609 1.        ]]


In [95]:
print(np.corrcoef(a_s2, out_h))
print(np.corrcoef(a_s2, out_e))
print(np.corrcoef(a_s2, out_l))

[[1.         0.04618718]
 [0.04618718 1.        ]]
[[ 1.         -0.03521161]
 [-0.03521161  1.        ]]
[[ 1.         -0.01447718]
 [-0.01447718  1.        ]]


In [96]:
print(np.corrcoef(a_el_m, out_h))
print(np.corrcoef(a_el_m, out_e))
print(np.corrcoef(a_el_m, out_l))

[[1.         0.03636969]
 [0.03636969 1.        ]]
[[ 1.         -0.01613741]
 [-0.01613741  1.        ]]
[[ 1.         -0.02280316]
 [-0.02280316  1.        ]]


In [97]:
print(np.corrcoef(a_hyd_m, out_h))
print(np.corrcoef(a_hyd_m, out_e))
print(np.corrcoef(a_hyd_m, out_l))

[[ 1.         -0.11087162]
 [-0.11087162  1.        ]]
[[1.         0.05904469]
 [0.05904469 1.        ]]
[[1.         0.05982263]
 [0.05982263 1.        ]]


In [98]:
print(np.corrcoef(a_pol_m, out_h))
print(np.corrcoef(a_pol_m, out_e))
print(np.corrcoef(a_pol_m, out_l))

[[ 1.         -0.14806441]
 [-0.14806441  1.        ]]
[[1.         0.04980339]
 [0.04980339 1.        ]]
[[1.         0.10847171]
 [0.10847171 1.        ]]


In [99]:
print(np.corrcoef(a_vol_m, out_h))
print(np.corrcoef(a_vol_m, out_e))
print(np.corrcoef(a_vol_m, out_l))

[[ 1.         -0.09196773]
 [-0.09196773  1.        ]]
[[1.         0.06918042]
 [0.06918042 1.        ]]
[[1.         0.02974469]
 [0.02974469 1.        ]]


In [100]:
print(np.corrcoef(a_s0_m, out_h))
print(np.corrcoef(a_s0_m, out_e))
print(np.corrcoef(a_s0_m, out_l))

[[ 1.         -0.05504439]
 [-0.05504439  1.        ]]
[[1.         0.07837798]
 [0.07837798 1.        ]]
[[ 1.         -0.01857478]
 [-0.01857478  1.        ]]


In [101]:
print(np.corrcoef(a_s1_m, out_h))
print(np.corrcoef(a_s1_m, out_e))
print(np.corrcoef(a_s1_m, out_l))

[[1.         0.11746915]
 [0.11746915 1.        ]]
[[ 1.         -0.08315817]
 [-0.08315817  1.        ]]
[[ 1.         -0.04311383]
 [-0.04311383  1.        ]]


In [102]:
print(np.corrcoef(a_s2_m, out_h))
print(np.corrcoef(a_s2_m, out_e))
print(np.corrcoef(a_s2_m, out_l))

[[ 1.         -0.16428047]
 [-0.16428047  1.        ]]
[[ 1.         -0.00583869]
 [-0.00583869  1.        ]]
[[1.        0.1804654]
 [0.1804654 1.       ]]


In [110]:
def get_seq_num_and_pos(ind: int):
    s = 0
    for i, l in enumerate(seq_len_test.tolist()):
        if s + l > ind:
            return i, int(ind - s)
        else:
            s += l

In [111]:
with open('proc_data.csv', 'w') as f:
    for i in range(vol.shape[0]):
        ind, pos = get_seq_num_and_pos(i)
        f.write(f"{ind};{pos};{el[i]};{hyd[i]};{pol[i]};{vol[i]};{s0[i]};{s1[i]};{s2[i]};{el_m[i]};{hyd_m[i]};{pol_m[i]};{vol_m[i]};{s0_m[i]};{s1_m[i]}" + 
                f";{s2_m[i]};{r_h[i]};{r_e[i]};{r_l[i]};{out_h[i]};{out_e[i]};{out_l[i]}\n")
    